image: docker:latest

services:
  - docker:dind

stages:
  - deploy

before_script:
  - apk update && apk add bash

step-deploy-prod:
  stage: deploy
  only:
    - production
  script:
    - bash ./deploy.sh
    # - sudo docker image prune -f
  environment: production
  when: manual
