image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - deploy

before_script:
  - docker info
  - apk update && apk add bash

step-deploy-prod:
  stage: deploy
  only:
    - production
  script:
    - bash ./deploy.sh
  environment: production
  # when: manual
