image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - deploy

before_script:
  - docker info
  # - apk update && apk add bash

step-deploy-prod:
  stage: deploy
  only:
    - production
  script:
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    # - sudo pip3 install docker-compose
    # - sudo docker-compose up -d
  environment: production
  # when: manual
